prefix = "iburguer"
vpc_cidr_block = "10.0.0.0/16"
db_name = "iburguer"
db_engine = "postgres"
db_engine_version = "16.1"
db_user = "iburguer"
db_password = "p1VTSsrRWKzYp1VTSsrRWKzY"

mongodbatlas_public_key = ""
mongodbatlas_private_key = ""